routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware('web')->group(function () {
    Route::get('/', [App\Http\Controllers\MainPageController::class, 'index'])
        ->name('main.page');

    Route::get('/catalog/{category:id?}', [App\Http\Controllers\CatalogController::class, 'index'])
        ->name('catalog.index');

    Route::get('/item/{item}', [App\Http\Controllers\ItemsController::class, 'show'])->name('items.show');

    Auth::routes();
});

Route::middleware(['web', 'csrf'])->group(function () {
    // Ваши маршруты, которые будут защищены CSRF
    Route::middleware(['auth'])->group(function () {
        /*
        * User
        **/
        Route::get(
            '/home',
            [App\Http\Controllers\AccountController::class, 'index']
        )->name('home');

        Route::get(
            '/settings',
            [App\Http\Controllers\AccountController::class, 'settings']
        )->name('account.settings');

        Route::post(
            '/change-password',
            [App\Http\Controllers\AccountController::class, 'changePassword']
        )->name('change.password');

        Route::put(
            '/user/update',
            [App\Http\Controllers\AccountController::class, 'updateUser']
        )->name('user.update');

        Route::put(
            '/user/status-update',
            [App\Http\Controllers\AccountController::class, 'updateUserStatus']
        )->name('user.status-update');

        /*
         * Shop
         * */
        Route::resource('shops', App\Http\Controllers\ShopController::class);

        /*
         * Seller Items
         * */
        Route::get(
            'seller-items/{shopId}',
            [App\Http\Controllers\SellerItemsController::class, 'index']
        )->name('seller.items.index');
        Route::get(
            '/seller-item-create/{shopId}',
            [App\Http\Controllers\SellerItemsController::class, 'create']
        )->name('seller-item.create');
        Route::get(
            'seller-item-edit/{item}',
            [App\Http\Controllers\SellerItemsController::class, 'edit']
        )->name('seller-item.edit');
        Route::post(
            'seller-item-store',
            [App\Http\Controllers\SellerItemsController::class, 'store']
        )->name('seller-item.store');
        Route::put(
            'seller-item-update/{item}',
            [App\Http\Controllers\SellerItemsController::class, 'update']
        )->name('seller-item.update');
        Route::delete(
            'seller-item-destroy/{item}',
            [App\Http\Controllers\SellerItemsController::class, 'destroy']
        )->name('seller-item.destroy');
    });

    Route::post(
        '/order/create',
        [App\Http\Controllers\OrdersController::class, 'create']
    )->name('orderCreate');

    Route::post(
        '/order/check-payment',
        [App\Http\Controllers\OrdersController::class, 'checkPayment']
    )->name('orderCheckPayment');
});

app/Models/Shop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Shop extends Model
{
    use HasFactory;

    const PHYSICAL_TYPE = 0;
    const ELECTRONIC_TYPE = 1;

    const STATUS_BLOCKED = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_VACATION = 2;
    CONST STATUSES_AVAILABLE_FOR_CHANGE = [
        self::STATUS_ACTIVE, self::STATUS_VACATION,
    ];

    protected $fillable = [
        'user_id',
        'type',
        'status',
        'name',
        'logo',
        'description',
        'contacts',
    ];

    public static function getById($id)
    {
        return DB::table('shops')
            ->where('id', $id)
            ->first();
    }
}

app/Http/Controllers/Api/ShopController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Shop;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ShopController extends Controller
{
    public function checkById(Request $request): JsonResponse
    {
        $rules = [
            'shopId' => 'required|integer',
        ];
        $messages = [
            'shopId' => 'Not valid shop ID.',
        ];

        $requestData = $request->all();

        $validator = Validator::make($requestData, $rules, $messages);
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $shopId = $request->input('shopId');
        $shop = Shop::where('id', $shopId)
            ->select("id", "user_id", "type", "status", "name", "created_at")
            ->first();

        return response()->json(['shop' => $shop]);
    }
}

app/Http/Controllers/ShopController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\UrlHelper;
use App\Models\Shop;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\File;
use Illuminate\Validation\Rule;

class ShopController extends Controller
{
    public function index()
    {
        $shops = Shop::where('user_id', Auth::id())->get()->all();
        return view('shops.index', compact('shops'));
    }

    public function create()
    {
        return view('shops.create');
    }

    public function store(Request $request)
    {
        $rules = [
//            'type' => 'required|in:0,1',
            'status' => [
                'required',
                'integer',
                Rule::in(Shop::STATUSES_AVAILABLE_FOR_CHANGE),
            ],
            'name' => 'required|string|max:255',
            'logo' => 'nullable|image|mimes:jpeg,png,jpg|max:1024',
            'description' => 'nullable|string',
            'contacts' => 'nullable|string',
        ];
        $messages = [
//            'type.required' => 'Данное поле - обязательное для заполнения.',
//            'type.in' => 'Не корректный тип магазина.',
            'status.required' => 'Данное поле - обязательное для заполнения.',
            'status' => 'Не корректный статус магазина.',
            'name.required' => 'Данное поле - обязательное для заполнения.',
            'name.max' => 'Слишком длинное название магазина.',
            'logo.image' => 'Данный файл не является изображением.',
            'logo.mimes' => 'Допустимы лишь следующие форматы изображения: jpeg,png,jpg.',
            'logo.max' => 'Изображение должно быть не более 1MB.',
        ];

        $requestData = $request->all();

        $validator = Validator::make($requestData, $rules, $messages);
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $requestData['user_id'] = Auth::id();
        $requestData['type'] = 1;
        $requestData['logo'] = "/app-images/shop-logo.jpg";

        // Save logo image
        if ($request->hasFile('logo')) {
            $logoFile = $request->file('logo');
            $userId = Auth::id();
            $fileName = time() . "-" . $userId . "." . $logoFile->getClientOriginalExtension();
            $folder = UrlHelper::makePathForImage();

            if($logoFile->move(public_path($folder), $fileName)) {
                $requestData['logo'] = "/" . $folder . "/" . $fileName;
            }
        }

        Shop::create($requestData);
        Session::flash('success', 'Магазин успешно создан');

        return response()->json(['success' => 'Магазин успешно создан'], 200);
    }

    public function show(Shop $shop)
    {
        return redirect()->route('shops.index');
    }

    public function edit(Shop $shop)
    {
        return view('shops.edit', compact('shop'));
    }

    public function update(Request $request, Shop $shop)
    {
        $oldLogo = trim($shop->logo, "/");

        $rules = [
            'status' => [
                'required',
                'integer',
                Rule::in(Shop::STATUSES_AVAILABLE_FOR_CHANGE),
            ],
            'name' => 'required|string|max:255',
            'logo' => 'nullable|image|mimes:jpeg,png,jpg|max:1024',
            'description' => 'nullable|string',
            'contacts' => 'nullable|string',
        ];
        $messages = [
            'status.required' => 'Данное поле - обязательное для заполнения.',
            'status' => 'Не корректный статус магазина.',
            'name.required' => 'Данное поле - обязательное для заполнения.',
            'name.max' => 'Слишком длинное название магазина.',
            'logo.image' => 'Данный файл не является изображением.',
            'logo.mimes' => 'Допустимы лишь следующие форматы изображения: jpeg,png,jpg.',
            'logo.max' => 'Изображение должно быть не более 1MB.',
        ];

        $requestData = $request->all();

        if ($shop->status == 3) {
            return response()->json(['errors' => ['status' => [0 => 'Магазин заблокирован, его редактировать нельзя']]], 422);
        }

        $validator = Validator::make($requestData, $rules, $messages);
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        // Save logo image
        if ($request->hasFile('logo')) {
            $logoFile = $request->file('logo');
            $userId = Auth::id();
            $fileName = time() . "-" . $userId . "." . $logoFile->getClientOriginalExtension();
            $folder = UrlHelper::makePathForImage();

            if($logoFile->move(public_path($folder), $fileName)) {
                $requestData['logo'] = "/" . $folder . "/" . $fileName;

                // Remove old logo
                if (File::exists($oldLogo) && !UrlHelper::isDefaultLogo($oldLogo)) {
                    File::delete($oldLogo);
                }
            }
        }

        $shop->update($requestData);

        return response()->json(['message' => 'Магазин успешно обновлен'], 200);
    }

    public function destroy(Shop $shop)
    {
        $shop->delete();

        return redirect()->route('shops.index')->with('success', 'Магазин успешно удален');
    }
}

resources/views/shops/create.blade.php
@extends('layouts.app')
@section('title', 'New Store')

@section('content')
    <div class="container mt-5">
        <h2>Create Shop</h2>

        <!-- Форма создания магазина -->
        <form id="saveShopData" action="{{ route('shops.store') }}" method="POST" enctype='multipart/form-data'>
            @csrf
            @include('shops.partials.form-fields', [ 'shop' => null ])
        </form>
    </div>
@endsection

@push('scripts')
    @vite('resources/js/shop/save.js')
@endpush

resources/views/shops/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit Store')

@section('content')
    <div class="container mt-5">
        <h2>Edit Shop</h2>

        <!-- Форма редактирования магазина -->
        <form id="updateShopData" action="{{ route('shops.update', $shop->id) }}" method="POST" enctype='multipart/form-data'>
            @csrf
            @method('PUT')

            @include('shops.partials.form-fields')
        </form>
    </div>

@endsection

@push('scripts')
    @vite('resources/js/shop/save.js')
@endpush

resources/views/shops/index.blade.php
@extends('layouts.app')
@section('title', 'Stores')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <h2>Shops List</h2>

            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a href="{{ route('shops.create') }}" type="button" class="btn btn-success">Create</a>
            </div>

            @if(empty($shops))
                <p>У вас пока нет магазинов.</p>
            @else
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>User ID</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($shops as $shop)
                    <tr>
                        <td>{{ $shop->id }}</td>
                        <td>{{ $shop->user_id }}</td>
                        <td>{{ $shop->type === 0 ? 'Standart (Physical Goods)' : 'Electronic' }}</td>
                        <td>
                            @if($shop->status === 0)
                                Blocked
                            @elseif($shop->status === 1)
                                Active
                            @else
                                Vacation
                            @endif
                        </td>
                        <td>{{ $shop->name }}</td>
                        <td>
                            <a href="{{ route('seller.items.index', $shop->id) }}" class="btn btn-secondary">Items</a>
                            <a href="{{ route('shops.edit', $shop->id) }}" class="btn btn-warning">Edit</a>
                            <form action="{{ route('shops.destroy', $shop->id) }}" method="POST" class="d-inline">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            @endif
        </div>
    </div>
@endsection