routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware('web')->group(function () {
    Route::get('/', [App\Http\Controllers\MainPageController::class, 'index'])
        ->name('main.page');

    Route::get('/catalog/{category:id?}', [App\Http\Controllers\CatalogController::class, 'index'])
        ->name('catalog.index');

    Route::get('/item/{item}', [App\Http\Controllers\ItemsController::class, 'show'])->name('items.show');

    Auth::routes();
});

Route::middleware(['web', 'csrf'])->group(function () {
    // Ваши маршруты, которые будут защищены CSRF
    Route::middleware(['auth'])->group(function () {
        /*
        * User
        **/
        Route::get(
            '/home',
            [App\Http\Controllers\AccountController::class, 'index']
        )->name('home');

        Route::get(
            '/settings',
            [App\Http\Controllers\AccountController::class, 'settings']
        )->name('account.settings');

        Route::post(
            '/change-password',
            [App\Http\Controllers\AccountController::class, 'changePassword']
        )->name('change.password');

        Route::put(
            '/user/update',
            [App\Http\Controllers\AccountController::class, 'updateUser']
        )->name('user.update');

        Route::put(
            '/user/status-update',
            [App\Http\Controllers\AccountController::class, 'updateUserStatus']
        )->name('user.status-update');

        /*
         * Shop
         * */
        Route::resource('shops', App\Http\Controllers\ShopController::class);

        /*
         * Seller Items
         * */
        Route::get(
            'seller-items/{shopId}',
            [App\Http\Controllers\SellerItemsController::class, 'index']
        )->name('seller.items.index');
        Route::get(
            '/seller-item-create/{shopId}',
            [App\Http\Controllers\SellerItemsController::class, 'create']
        )->name('seller-item.create');
        Route::get(
            'seller-item-edit/{item}',
            [App\Http\Controllers\SellerItemsController::class, 'edit']
        )->name('seller-item.edit');
        Route::post(
            'seller-item-store',
            [App\Http\Controllers\SellerItemsController::class, 'store']
        )->name('seller-item.store');
        Route::put(
            'seller-item-update/{item}',
            [App\Http\Controllers\SellerItemsController::class, 'update']
        )->name('seller-item.update');
        Route::delete(
            'seller-item-destroy/{item}',
            [App\Http\Controllers\SellerItemsController::class, 'destroy']
        )->name('seller-item.destroy');
    });

    Route::post(
        '/order/create',
        [App\Http\Controllers\OrdersController::class, 'create']
    )->name('orderCreate');

    Route::post(
        '/order/check-payment',
        [App\Http\Controllers\OrdersController::class, 'checkPayment']
    )->name('orderCheckPayment');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Shop
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('shops.index') }}">{{ __('Shops') }}</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>

                                    <a class="dropdown-item" href="{{ route('account.settings') }}">
                                        {{ __('Settings') }}
                                    </a>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <header class="py-4 container">
            @yield('header')
        </header>

        <main class="py-4 container">

            @yield('content')
        </main>
    </div>

    @if (session('success'))
        <script>
            const successMessage = '{{ session('success') }}';
        </script>
    @endif
    @if (session('error'))
        <script>
            const errorMessage = '{{ session('error') }}';
        </script>
    @endif

    @vite('resources/js/app.js')
    @stack('scripts')
</body>
</html>